export { default as Gemini } from './Gemini'
export { default as Replit } from './Replit'
export { default as MagicUI } from './MagicUI'
export { default as VSCodium } from './VSCodium'
export { default as MediaWiki } from './MediaWiki'
export { default as GooglePaLM } from './GooglePaLM'
export { default as Java }from'./Java'
export { default as Javascript } from './Javascript'
export { default as C } from './C++'
export { default as NET } from './NET'
export { default as Nextjs } from './Nextjs'
